### ISSUE TITLE
Add support for batch requests

### ISSUE THREAD

**Issue by edwlook** [edwlook/node-google-distance#5]
The Google API is able to return multiple distance elements with a single request.

For example: http://maps.googleapis.com/maps/api/distancematrix/json?origins=Vancouver+BC|Seattle&destinations=San+Francisco|Victoria+BC&mode=bicycling&language=fr-FR&sensor=false

More info: https://developers.google.com/maps/documentation/distancematrix/#JSON

**Comment by edwlook** [comment]
Added in #7.

**Comment by rajanand02** [comment]
is it possible to set waypoints? e.g souce: A, destination: X via: B and C,  so it can compute A -> B -> C -> X

**Comment by edwlook** [comment]
@rajanand02 The distance matrix API does not support waypoints, but you could mimic them by using separate calls (e.g. dist(A -> B) + dist(B -> C) + dist(C -> X)).

**Comment by rajanand02** [comment]
@edwlook oh okay btw thanks for the suggestions.
